<?php 
	echo '<html>';
	echo '<head>';
	echo '<title> SCE | Welcome</title>';
	echo '<link rel="stylesheet" type="text/css" href="css/main.css">';
	echo '<script type="text/javascript" src="js/jquery-1.8.2.min.js"></script>';
	echo '<script type="text/javascript" src="js/main.js"></script>';
	echo '</head>';
	echo '<body>';
	echo '<div id="navwrapper">';
	echo '<ul id="nav" class="floatleft">';
	echo '<li><a href="#">SCE +</a></li>';
	echo '<li><a class="current" href="http://sce.engr.sjsu.edu/">Home</a></li>';
	echo '<li><a href="#">Gallery</a></li>';
	echo '<li><a href="#">Forms</a></li>';
	echo '<li><a href="#" onclick="ajax_events()">Events</a></li>';
	echo '<li><a href="#" onclick="ajax_studies()">Studies</a></li>';
	echo '<li><a href="#" onclick="ajax_faq()">FAQ</a></li>';
	echo '<li><a href="#" onclick="ajax_about()">About</a></li>';
	echo '<li><a href="#" onclick="ajax_officers()">Officers</a></li>';
	echo '<li><a class="dmenu" href="#">More <span class="arrowdown">&#9660</span></a>';
	echo '<ul>';
	echo '<li><a href="#">Forums</a></li>';
	echo '<li><a href="#" onclick="ajax_conferences()">Conferences</a></li>';
	echo '<li><a href="alumniportal.php">Alumni Portal</a></li>';
	echo '</ul>';
	echo '</li>';
	echo '</ul>';
	echo '<br class="clear">';
	echo '</div>';
	echo '<div id="roundboxlogo">';
	echo '<div class="logocontent">';
	echo '<img height="125px" width="900px" style="border: 0px solid black;
            border-radius: 30px;
            -moz-border-radius: 30px;
            -khtml-border-radius: 30px;
            -webkit-border-radius: 30px;" src="images/scelogo.png"/>';
	echo '</div>';
	echo '</div>';
	echo '<div id="content">';
?>
